name: Chris Scholtens
favicon: null
layout_spectrum: 1
typography_spectrum: 0.76066
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#fc7203'
    - '#aaaaaa'
    - '#694a2e'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 1
purpose:
  - name: awareness
    item: null
    url: null
